<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.9.7
 */

/**
 * Database `holts`
 */

/* `holts`.`CUSTOMER` */
$CUSTOMER = array(
  array('CUSTOMER_NUM' => '1','CUSTOMER_NAME' => 'Tayyab Woodley','CUSTOMER_ADDRESS1' => '75 Old Greystone St.','CUSTOMER_ADDRESS2' => 'Suite 2','CUSTOMER_CITY' => 'Brookfield','CUSTOMER_STATE' => 'WI','CUSTOMER_ZIP' => '53045','MTDSALES' => '4766.34','YTDSALES' => '61445.76','CURRENT_BALANCE' => '3412.45','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Yasmine Macias','SHIPPING_ADDRESS1' => '9625 Rockland Dr.','SHIPPING_ADDRESS2' => 'Suite R','SHIPPING_CITY' => 'Londonderry','SHIPPING_STATE' => 'NH','SHIPPING_ZIP' => '3053','INVOICE_TOTAL' => '20769.17','PAYMENT_TOTAL' => '20769.17','CURRENT_AMOUNT' => '3412.45','PREVIOUS_BALANCE' => '3412.45','TERRITORY_NUM' => '10','SALES_REP_ID' => '4'),
  array('CUSTOMER_NUM' => '2','CUSTOMER_NAME' => 'Nel Holden','CUSTOMER_ADDRESS1' => '668 Lilac Dr.','CUSTOMER_ADDRESS2' => 'Fl 3','CUSTOMER_CITY' => 'North Haven','CUSTOMER_STATE' => 'CT','CUSTOMER_ZIP' => '6473','MTDSALES' => '2564.65','YTDSALES' => '5256.45','CURRENT_BALANCE' => '526.76','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Amaan Carlson','SHIPPING_ADDRESS1' => '21 West Newport Court','SHIPPING_ADDRESS2' => 'Suite 3','SHIPPING_CITY' => 'Randallstown','SHIPPING_STATE' => 'MD','SHIPPING_ZIP' => '21133','INVOICE_TOTAL' => '1844.97','PAYMENT_TOTAL' => '1844.97','CURRENT_AMOUNT' => '526.76','PREVIOUS_BALANCE' => '526.76','TERRITORY_NUM' => '10','SALES_REP_ID' => '8'),
  array('CUSTOMER_NUM' => '3','CUSTOMER_NAME' => 'Xena McCall','CUSTOMER_ADDRESS1' => '17 Ketch Harbour Rd.','CUSTOMER_ADDRESS2' => 'Apt 5','CUSTOMER_CITY' => 'Westport','CUSTOMER_STATE' => 'CT','CUSTOMER_ZIP' => '6880','MTDSALES' => '425.56','YTDSALES' => '2956.45','CURRENT_BALANCE' => '1646.54','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Ajwa Cowan','SHIPPING_ADDRESS1' => '892 Princess St.','SHIPPING_ADDRESS2' => 'Apt 4C','SHIPPING_CITY' => 'King of Prussia','SHIPPING_STATE' => 'PA','SHIPPING_ZIP' => '19406','INVOICE_TOTAL' => '0.00','PAYMENT_TOTAL' => '0.00','CURRENT_AMOUNT' => '1646.54','PREVIOUS_BALANCE' => '1646.54','TERRITORY_NUM' => '7','SALES_REP_ID' => '10'),
  array('CUSTOMER_NUM' => '4','CUSTOMER_NAME' => 'Fearne Whitworth','CUSTOMER_ADDRESS1' => '8 Warren St.','CUSTOMER_ADDRESS2' => 'Apt 5','CUSTOMER_CITY' => 'Loveland','CUSTOMER_STATE' => 'OH','CUSTOMER_ZIP' => '45140','MTDSALES' => '425.45','YTDSALES' => '2496.46','CURRENT_BALANCE' => '287.45','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Aled Blevins','SHIPPING_ADDRESS1' => '8204 SW. Princess Ave.','SHIPPING_ADDRESS2' => 'Suite 3','SHIPPING_CITY' => 'Algonquin','SHIPPING_STATE' => 'IL','SHIPPING_ZIP' => '60102','INVOICE_TOTAL' => '0.00','PAYMENT_TOTAL' => '0.00','CURRENT_AMOUNT' => '287.45','PREVIOUS_BALANCE' => '287.45','TERRITORY_NUM' => '2','SALES_REP_ID' => '3'),
  array('CUSTOMER_NUM' => '5','CUSTOMER_NAME' => 'Bernice Osborn','CUSTOMER_ADDRESS1' => '2 Birchwood St.','CUSTOMER_ADDRESS2' => 'Apt 20','CUSTOMER_CITY' => 'North Ridgeville','CUSTOMER_STATE' => 'OH','CUSTOMER_ZIP' => '44039','MTDSALES' => '1275.56','YTDSALES' => '5245.63','CURRENT_BALANCE' => '974.74','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Morgan Marquez','SHIPPING_ADDRESS1' => '7883 53rd Dr.','SHIPPING_ADDRESS2' => 'Apt 7','SHIPPING_CITY' => 'Klamath Falls','SHIPPING_STATE' => 'OR','SHIPPING_ZIP' => '97603','INVOICE_TOTAL' => '1906.40','PAYMENT_TOTAL' => '1906.40','CURRENT_AMOUNT' => '974.74','PREVIOUS_BALANCE' => '974.74','TERRITORY_NUM' => '6','SALES_REP_ID' => '9'),
  array('CUSTOMER_NUM' => '6','CUSTOMER_NAME' => 'Muhamed Domingue','CUSTOMER_ADDRESS1' => '9291 Bald Hill Rd.','CUSTOMER_ADDRESS2' => 'Suite 1','CUSTOMER_CITY' => 'Westlake','CUSTOMER_STATE' => 'OH','CUSTOMER_ZIP' => '44145','MTDSALES' => '134.34','YTDSALES' => '645.23','CURRENT_BALANCE' => '346.45','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Aayan Akhtar','SHIPPING_ADDRESS1' => '480 Plymouth Dr.','SHIPPING_ADDRESS2' => 'Fl 3','SHIPPING_CITY' => 'Roy','SHIPPING_STATE' => 'UT','SHIPPING_ZIP' => '84067','INVOICE_TOTAL' => '0.00','PAYMENT_TOTAL' => '0.00','CURRENT_AMOUNT' => '346.45','PREVIOUS_BALANCE' => '346.45','TERRITORY_NUM' => '4','SALES_REP_ID' => '1'),
  array('CUSTOMER_NUM' => '7','CUSTOMER_NAME' => 'Nabila Weiss','CUSTOMER_ADDRESS1' => '736 Peachtree Ave.','CUSTOMER_ADDRESS2' => 'Fl 2','CUSTOMER_CITY' => 'Coventry','CUSTOMER_STATE' => 'RI','CUSTOMER_ZIP' => '2816','MTDSALES' => '1837.45','YTDSALES' => '28454.46','CURRENT_BALANCE' => '3684.34','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Emanuel Simmonds','SHIPPING_ADDRESS1' => '19 Ridgeview Dr.','SHIPPING_ADDRESS2' => 'Suite 4','SHIPPING_CITY' => 'Maineville','SHIPPING_STATE' => 'OH','SHIPPING_ZIP' => '45039','INVOICE_TOTAL' => '6764.11','PAYMENT_TOTAL' => '6764.11','CURRENT_AMOUNT' => '3684.34','PREVIOUS_BALANCE' => '3684.34','TERRITORY_NUM' => '8','SALES_REP_ID' => '6'),
  array('CUSTOMER_NUM' => '8','CUSTOMER_NAME' => 'Chanelle Morris','CUSTOMER_ADDRESS1' => '9631 Cambridge St.','CUSTOMER_ADDRESS2' => 'Suite 3','CUSTOMER_CITY' => 'Marshfield','CUSTOMER_STATE' => 'WI','CUSTOMER_ZIP' => '54449','MTDSALES' => '23.45','YTDSALES' => '423.76','CURRENT_BALANCE' => '267.45','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Amari Bird','SHIPPING_ADDRESS1' => '627 Mechanic St.','SHIPPING_ADDRESS2' => 'Apt 2','SHIPPING_CITY' => 'West Bloomfield','SHIPPING_STATE' => 'MI','SHIPPING_ZIP' => '48322','INVOICE_TOTAL' => '0.00','PAYMENT_TOTAL' => '0.00','CURRENT_AMOUNT' => '267.45','PREVIOUS_BALANCE' => '267.45','TERRITORY_NUM' => '9','SALES_REP_ID' => '7'),
  array('CUSTOMER_NUM' => '9','CUSTOMER_NAME' => 'Walter Michael','CUSTOMER_ADDRESS1' => '198 Redwood Rd.','CUSTOMER_ADDRESS2' => 'Apt 5','CUSTOMER_CITY' => 'Minneapolis','CUSTOMER_STATE' => 'MN','CUSTOMER_ZIP' => '55406','MTDSALES' => '7457.83','YTDSALES' => '34452.97','CURRENT_BALANCE' => '12042.03','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Conall Lawson','SHIPPING_ADDRESS1' => '8341 Ann St.','SHIPPING_ADDRESS2' => 'Apt 6','SHIPPING_CITY' => 'Allison Park','SHIPPING_STATE' => 'PA','SHIPPING_ZIP' => '15101','INVOICE_TOTAL' => '9902.34','PAYMENT_TOTAL' => '1818.76','CURRENT_AMOUNT' => '12042.03','PREVIOUS_BALANCE' => '3958.45','TERRITORY_NUM' => '5','SALES_REP_ID' => '5'),
  array('CUSTOMER_NUM' => '10','CUSTOMER_NAME' => 'Danyal Ashley','CUSTOMER_ADDRESS1' => '36 Main St.','CUSTOMER_ADDRESS2' => 'Apt 8','CUSTOMER_CITY' => 'Wappingers Falls','CUSTOMER_STATE' => 'NY','CUSTOMER_ZIP' => '12590','MTDSALES' => '2456.45','YTDSALES' => '5646.45','CURRENT_BALANCE' => '2398.72','CREDIT_LIMIT' => '1000000.00','SHIPPING_NAME' => 'Gregg Mooney','SHIPPING_ADDRESS1' => '8379 Wrangler Lane','SHIPPING_ADDRESS2' => 'Apt 12','SHIPPING_CITY' => 'Amsterdam','SHIPPING_STATE' => 'NY','SHIPPING_ZIP' => '12010','INVOICE_TOTAL' => '1723.38','PAYMENT_TOTAL' => '0.00','CURRENT_AMOUNT' => '2398.72','PREVIOUS_BALANCE' => '675.34','TERRITORY_NUM' => '7','SALES_REP_ID' => '10')
);

/* `holts`.`INVOICE` */
$INVOICE = array(
  array('INVOICE_NUM' => '17','INVOICE_DATE' => '2019-11-14','INVOICE_TOTAL' => '6764.11','INVOICE_SHIPPING' => '35.00','INVOICE_TAX' => '28','CUSTOMER_NUM' => '7','ORDER_NUM' => '4'),
  array('INVOICE_NUM' => '18','INVOICE_DATE' => '2019-12-01','INVOICE_TOTAL' => '328.83','INVOICE_SHIPPING' => '25.00','INVOICE_TAX' => '24','CUSTOMER_NUM' => '9','ORDER_NUM' => '10'),
  array('INVOICE_NUM' => '19','INVOICE_DATE' => '2019-12-15','INVOICE_TOTAL' => '1906.40','INVOICE_SHIPPING' => '25.00','INVOICE_TAX' => '27','CUSTOMER_NUM' => '5','ORDER_NUM' => '3'),
  array('INVOICE_NUM' => '20','INVOICE_DATE' => '2020-01-06','INVOICE_TOTAL' => '9655.99','INVOICE_SHIPPING' => '17.00','INVOICE_TAX' => '15','CUSTOMER_NUM' => '1','ORDER_NUM' => '9'),
  array('INVOICE_NUM' => '21','INVOICE_DATE' => '2020-01-25','INVOICE_TOTAL' => '5757.22','INVOICE_SHIPPING' => '27.50','INVOICE_TAX' => '22','CUSTOMER_NUM' => '1','ORDER_NUM' => '5'),
  array('INVOICE_NUM' => '22','INVOICE_DATE' => '2020-01-25','INVOICE_TOTAL' => '1489.93','INVOICE_SHIPPING' => '32.00','INVOICE_TAX' => '27','CUSTOMER_NUM' => '9','ORDER_NUM' => '8'),
  array('INVOICE_NUM' => '23','INVOICE_DATE' => '2020-05-20','INVOICE_TOTAL' => '8083.58','INVOICE_SHIPPING' => '23.75','INVOICE_TAX' => '16','CUSTOMER_NUM' => '9','ORDER_NUM' => '6'),
  array('INVOICE_NUM' => '24','INVOICE_DATE' => '2020-05-20','INVOICE_TOTAL' => '5355.96','INVOICE_SHIPPING' => '17.00','INVOICE_TAX' => '13','CUSTOMER_NUM' => '1','ORDER_NUM' => '1')
);

/* `holts`.`ORDERS` */
$ORDERS = array(
  array('ORDER_NUM' => '11','ORDER_DATE' => '2020-04-14','ORDER_COMMENTS' => ' ','CUSTOMER_PO_NUM' => 'PO45345','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '1','SPECIAL_CHARGE_NUM' => '4'),
  array('ORDER_NUM' => '12','ORDER_DATE' => '2020-06-26','ORDER_COMMENTS' => 'Color: Blue','CUSTOMER_PO_NUM' => 'PO869506','ORDER_STATUS' => 'OPEN','CUSTOMER_NUM' => '2','SPECIAL_CHARGE_NUM' => '7'),
  array('ORDER_NUM' => '13','ORDER_DATE' => '2019-12-10','ORDER_COMMENTS' => ' ','CUSTOMER_PO_NUM' => ' ','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '5','SPECIAL_CHARGE_NUM' => '6'),
  array('ORDER_NUM' => '14','ORDER_DATE' => '2019-10-23','ORDER_COMMENTS' => ' ','CUSTOMER_PO_NUM' => ' ','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '7','SPECIAL_CHARGE_NUM' => '7'),
  array('ORDER_NUM' => '15','ORDER_DATE' => '2020-01-04','ORDER_COMMENTS' => 'Size: Large','CUSTOMER_PO_NUM' => 'PO13906','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '1','SPECIAL_CHARGE_NUM' => '9'),
  array('ORDER_NUM' => '16','ORDER_DATE' => '2020-03-29','ORDER_COMMENTS' => ' ','CUSTOMER_PO_NUM' => 'PO8495','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '9','SPECIAL_CHARGE_NUM' => '5'),
  array('ORDER_NUM' => '17','ORDER_DATE' => '2019-12-10','ORDER_COMMENTS' => 'Size: Medium','CUSTOMER_PO_NUM' => ' ','ORDER_STATUS' => 'OPEN','CUSTOMER_NUM' => '10','SPECIAL_CHARGE_NUM' => '4'),
  array('ORDER_NUM' => '18','ORDER_DATE' => '2020-01-04','ORDER_COMMENTS' => 'Size: Large','CUSTOMER_PO_NUM' => ' ','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '9','SPECIAL_CHARGE_NUM' => '7'),
  array('ORDER_NUM' => '19','ORDER_DATE' => '2019-12-10','ORDER_COMMENTS' => 'Color: Black','CUSTOMER_PO_NUM' => ' ','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '1','SPECIAL_CHARGE_NUM' => '5'),
  array('ORDER_NUM' => '20','ORDER_DATE' => '2019-10-23','ORDER_COMMENTS' => ' ','CUSTOMER_PO_NUM' => 'PO2576','ORDER_STATUS' => 'CLOSED','CUSTOMER_NUM' => '9','SPECIAL_CHARGE_NUM' => '2')
);

/* `holts`.`ORDER_DETAILS` */
$ORDER_DETAILS = array(
  array('ORDER_DETAIL_NUM' => '41','NUMBER_ORDERED' => '5','QUOTED_PRICE' => '219.76','PART_NUM' => '5','ORDER_NUM' => '9'),
  array('ORDER_DETAIL_NUM' => '42','NUMBER_ORDERED' => '4','QUOTED_PRICE' => '764.23','PART_NUM' => '4','ORDER_NUM' => '6'),
  array('ORDER_DETAIL_NUM' => '43','NUMBER_ORDERED' => '8','QUOTED_PRICE' => '209.38','PART_NUM' => '8','ORDER_NUM' => '7'),
  array('ORDER_DETAIL_NUM' => '44','NUMBER_ORDERED' => '5','QUOTED_PRICE' => '85.45','PART_NUM' => '1','ORDER_NUM' => '9'),
  array('ORDER_DETAIL_NUM' => '45','NUMBER_ORDERED' => '10','QUOTED_PRICE' => '85.45','PART_NUM' => '1','ORDER_NUM' => '1'),
  array('ORDER_DETAIL_NUM' => '46','NUMBER_ORDERED' => '8','QUOTED_PRICE' => '219.76','PART_NUM' => '5','ORDER_NUM' => '2'),
  array('ORDER_DETAIL_NUM' => '47','NUMBER_ORDERED' => '7','QUOTED_PRICE' => '387.35','PART_NUM' => '10','ORDER_NUM' => '6'),
  array('ORDER_DETAIL_NUM' => '48','NUMBER_ORDERED' => '1','QUOTED_PRICE' => '209.38','PART_NUM' => '8','ORDER_NUM' => '10'),
  array('ORDER_DETAIL_NUM' => '49','NUMBER_ORDERED' => '8','QUOTED_PRICE' => '476.87','PART_NUM' => '9','ORDER_NUM' => '4'),
  array('ORDER_DETAIL_NUM' => '50','NUMBER_ORDERED' => '15','QUOTED_PRICE' => '123.65','PART_NUM' => '2','ORDER_NUM' => '3'),
  array('ORDER_DETAIL_NUM' => '51','NUMBER_ORDERED' => '3','QUOTED_PRICE' => '229.38','PART_NUM' => '8','ORDER_NUM' => '9'),
  array('ORDER_DETAIL_NUM' => '52','NUMBER_ORDERED' => '18','QUOTED_PRICE' => '123.65','PART_NUM' => '2','ORDER_NUM' => '6'),
  array('ORDER_DETAIL_NUM' => '53','NUMBER_ORDERED' => '10','QUOTED_PRICE' => '219.76','PART_NUM' => '5','ORDER_NUM' => '1'),
  array('ORDER_DETAIL_NUM' => '54','NUMBER_ORDERED' => '4','QUOTED_PRICE' => '387.35','PART_NUM' => '10','ORDER_NUM' => '9'),
  array('ORDER_DETAIL_NUM' => '55','NUMBER_ORDERED' => '9','QUOTED_PRICE' => '634.23','PART_NUM' => '3','ORDER_NUM' => '5'),
  array('ORDER_DETAIL_NUM' => '56','NUMBER_ORDERED' => '2','QUOTED_PRICE' => '123.65','PART_NUM' => '2','ORDER_NUM' => '1'),
  array('ORDER_DETAIL_NUM' => '57','NUMBER_ORDERED' => '6','QUOTED_PRICE' => '329.45','PART_NUM' => '6','ORDER_NUM' => '1'),
  array('ORDER_DETAIL_NUM' => '58','NUMBER_ORDERED' => '3','QUOTED_PRICE' => '476.87','PART_NUM' => '9','ORDER_NUM' => '8'),
  array('ORDER_DETAIL_NUM' => '59','NUMBER_ORDERED' => '15','QUOTED_PRICE' => '190.76','PART_NUM' => '5','ORDER_NUM' => '4'),
  array('ORDER_DETAIL_NUM' => '60','NUMBER_ORDERED' => '18','QUOTED_PRICE' => '359.45','PART_NUM' => '6','ORDER_NUM' => '9')
);

/* `holts`.`PART` */
$PART = array(
  array('PART_NUM' => '1','PART_DESCRIPTION' => 'T-Shirt','UNIT_PRICE' => '85.45','MTDSALES' => '2221.70','YTDSALES' => '14114.10','UNITS_ONHAND' => '53','UNITS_ALLOCATED' => '15','REORDER_POINT' => '125','NOTES' => '*'),
  array('PART_NUM' => '2','PART_DESCRIPTION' => 'Sweatpant','UNIT_PRICE' => '123.65','MTDSALES' => '8284.55','YTDSALES' => '105226.15','UNITS_ONHAND' => '576','UNITS_ALLOCATED' => '35','REORDER_POINT' => '200','NOTES' => ' '),
  array('PART_NUM' => '3','PART_DESCRIPTION' => 'Jacket','UNIT_PRICE' => '634.23','MTDSALES' => '32979.96','YTDSALES' => '413517.96','UNITS_ONHAND' => '546','UNITS_ALLOCATED' => '9','REORDER_POINT' => '200','NOTES' => ' '),
  array('PART_NUM' => '4','PART_DESCRIPTION' => 'Coat','UNIT_PRICE' => '764.23','MTDSALES' => '32097.66','YTDSALES' => '261366.66','UNITS_ONHAND' => '91','UNITS_ALLOCATED' => '4','REORDER_POINT' => '150','NOTES' => '*'),
  array('PART_NUM' => '5','PART_DESCRIPTION' => 'Jeans','UNIT_PRICE' => '219.76','MTDSALES' => '18020.32','YTDSALES' => '90101.60','UNITS_ONHAND' => '286','UNITS_ALLOCATED' => '38','REORDER_POINT' => '125','NOTES' => ' '),
  array('PART_NUM' => '6','PART_DESCRIPTION' => 'Backpack','UNIT_PRICE' => '329.45','MTDSALES' => '20755.35','YTDSALES' => '172302.35','UNITS_ONHAND' => '494','UNITS_ALLOCATED' => '24','REORDER_POINT' => '75','NOTES' => ' '),
  array('PART_NUM' => '7','PART_DESCRIPTION' => 'Wallet','UNIT_PRICE' => '154.98','MTDSALES' => '13948.20','YTDSALES' => '112050.54','UNITS_ONHAND' => '41','UNITS_ALLOCATED' => '0','REORDER_POINT' => '150','NOTES' => '*'),
  array('PART_NUM' => '8','PART_DESCRIPTION' => 'Dress','UNIT_PRICE' => '209.38','MTDSALES' => '17169.16','YTDSALES' => '135050.10','UNITS_ONHAND' => '374','UNITS_ALLOCATED' => '12','REORDER_POINT' => '125','NOTES' => ' '),
  array('PART_NUM' => '9','PART_DESCRIPTION' => 'Hoodie','UNIT_PRICE' => '476.87','MTDSALES' => '17644.19','YTDSALES' => '200749.64','UNITS_ONHAND' => '265','UNITS_ALLOCATED' => '11','REORDER_POINT' => '150','NOTES' => ' '),
  array('PART_NUM' => '10','PART_DESCRIPTION' => 'Sneaker','UNIT_PRICE' => '387.35','MTDSALES' => '14719.30','YTDSALES' => '113493.55','UNITS_ONHAND' => '218','UNITS_ALLOCATED' => '11','REORDER_POINT' => '150','NOTES' => ' ')
);

/* `holts`.`PAYMENT` */
$PAYMENT = array(
  array('PAYMENT_NUM' => '1','PAYMENT_DATE' => '2019-12-15','PAYMENT_AMOUNT' => '328.83','CUSTOMER_NUM' => '9','INVOICE_NUM' => '2'),
  array('PAYMENT_NUM' => '2','PAYMENT_DATE' => '2020-01-25','PAYMENT_AMOUNT' => '6764.11','CUSTOMER_NUM' => '7','INVOICE_NUM' => '1'),
  array('PAYMENT_NUM' => '3','PAYMENT_DATE' => '2020-02-04','PAYMENT_AMOUNT' => '1906.40','CUSTOMER_NUM' => '5','INVOICE_NUM' => '3'),
  array('PAYMENT_NUM' => '4','PAYMENT_DATE' => '2020-02-04','PAYMENT_AMOUNT' => '1489.93','CUSTOMER_NUM' => '9','INVOICE_NUM' => '7'),
  array('PAYMENT_NUM' => '5','PAYMENT_DATE' => '2020-02-20','PAYMENT_AMOUNT' => '5757.22','CUSTOMER_NUM' => '9','INVOICE_NUM' => '6'),
  array('PAYMENT_NUM' => '6','PAYMENT_DATE' => '2020-06-17','PAYMENT_AMOUNT' => '8083.58','CUSTOMER_NUM' => '1','INVOICE_NUM' => '8'),
  array('PAYMENT_NUM' => '7','PAYMENT_DATE' => '2020-06-23','PAYMENT_AMOUNT' => '9655.99','CUSTOMER_NUM' => '1','INVOICE_NUM' => '5'),
  array('PAYMENT_NUM' => '8','PAYMENT_DATE' => '2020-07-28','PAYMENT_AMOUNT' => '5355.96','CUSTOMER_NUM' => '1','INVOICE_NUM' => '4')
);

/* `holts`.`SALES_REP` */
$SALES_REP = array(
  array('SALES_REP_ID' => '1','SALES_REP_NAME' => 'Gene Appleton','SALES_REP_ADDRESS' => '310 Wayne Str.','SALES_REP_CITY' => 'Malvern','SALES_REP_STATE' => 'PA','SALES_REP_ZIP' => '19355','MTDSALES' => '345.34','YTDSALES' => '7535.34','MTD_COMMISSION' => '18.30','YTD_COMMISSION' => '399.37','COMMISSION_RATE' => '0.05000','TERRITORY_NUM' => '4'),
  array('SALES_REP_ID' => '2','SALES_REP_NAME' => 'Elleanor Melton','SALES_REP_ADDRESS' => '63 Cooper Dr.','SALES_REP_CITY' => 'Lewiston','SALES_REP_STATE' => 'ME','SALES_REP_ZIP' => '04240','MTDSALES' => '8474.35','YTDSALES' => '35984.45','MTD_COMMISSION' => '661.00','YTD_COMMISSION' => '2806.79','COMMISSION_RATE' => '0.08000','TERRITORY_NUM' => '6'),
  array('SALES_REP_ID' => '3','SALES_REP_NAME' => 'Keiran Lott','SALES_REP_ADDRESS' => '9353 Annadale Dr.','SALES_REP_CITY' => 'Harvey','SALES_REP_STATE' => 'IL','SALES_REP_ZIP' => '06426','MTDSALES' => '1245.39','YTDSALES' => '4124.56','MTD_COMMISSION' => '150.69','YTD_COMMISSION' => '499.07','COMMISSION_RATE' => '0.12000','TERRITORY_NUM' => '2'),
  array('SALES_REP_ID' => '4','SALES_REP_NAME' => 'Francesca Morse','SALES_REP_ADDRESS' => '267 S. Third Ave.','SALES_REP_CITY' => 'Southfield','SALES_REP_STATE' => 'MI','SALES_REP_ZIP' => '48076','MTDSALES' => '65.23','YTDSALES' => '786.23','MTD_COMMISSION' => '0.78','YTD_COMMISSION' => '9.43','COMMISSION_RATE' => '0.01000','TERRITORY_NUM' => '10'),
  array('SALES_REP_ID' => '5','SALES_REP_NAME' => 'Chandler McCormick','SALES_REP_ADDRESS' => '8385 Hillcrest St.','SALES_REP_CITY' => 'Miami','SALES_REP_STATE' => 'FL','SALES_REP_ZIP' => '33125','MTDSALES' => '6567.34','YTDSALES' => '96434.34','MTD_COMMISSION' => '584.49','YTD_COMMISSION' => '8582.66','COMMISSION_RATE' => '0.09000','TERRITORY_NUM' => '5'),
  array('SALES_REP_ID' => '6','SALES_REP_NAME' => 'Clarice Bean','SALES_REP_ADDRESS' => '89 Kirkland Dr.','SALES_REP_CITY' => 'Grayslake','SALES_REP_STATE' => 'IL','SALES_REP_ZIP' => '60030','MTDSALES' => '742.45','YTDSALES' => '4653.45','MTD_COMMISSION' => '48.26','YTD_COMMISSION' => '302.47','COMMISSION_RATE' => '0.07000','TERRITORY_NUM' => '8'),
  array('SALES_REP_ID' => '7','SALES_REP_NAME' => 'Balraj Haynes','SALES_REP_ADDRESS' => '58 Thorne St.','SALES_REP_CITY' => 'Corpus Christi','SALES_REP_STATE' => 'TX','SALES_REP_ZIP' => '78418','MTDSALES' => '657.45','YTDSALES' => '24567.45','MTD_COMMISSION' => '32.22','YTD_COMMISSION' => '1203.81','COMMISSION_RATE' => '0.05000','TERRITORY_NUM' => '9'),
  array('SALES_REP_ID' => '8','SALES_REP_NAME' => 'Dawson Fellows','SALES_REP_ADDRESS' => '8078 Bellevue Dr.','SALES_REP_CITY' => 'Lansing','SALES_REP_STATE' => 'MI','SALES_REP_ZIP' => '48910','MTDSALES' => '1234.56','YTDSALES' => '44554.34','MTD_COMMISSION' => '67.90','YTD_COMMISSION' => '2450.49','COMMISSION_RATE' => '0.06000','TERRITORY_NUM' => '10'),
  array('SALES_REP_ID' => '9','SALES_REP_NAME' => 'Uma Blevins','SALES_REP_ADDRESS' => '55 DE. Ridge St.','SALES_REP_CITY' => 'Mokena','SALES_REP_STATE' => 'IL','SALES_REP_ZIP' => '60448','MTDSALES' => '967.56','YTDSALES' => '34456.43','MTD_COMMISSION' => '32.90','YTD_COMMISSION' => '1171.52','COMMISSION_RATE' => '0.03000','TERRITORY_NUM' => '6'),
  array('SALES_REP_ID' => '10','SALES_REP_NAME' => 'Fannie Riddle','SALES_REP_ADDRESS' => '47 Plymouth Ave.','SALES_REP_CITY' => 'Brighton','SALES_REP_STATE' => 'MA','SALES_REP_ZIP' => '02135','MTDSALES' => '8474.35','YTDSALES' => '35984.45','MTD_COMMISSION' => '661.00','YTD_COMMISSION' => '2806.79','COMMISSION_RATE' => '0.08000','TERRITORY_NUM' => '7')
);

/* `holts`.`SPECIAL_CHARGES` */
$SPECIAL_CHARGES = array(
  array('SPECIAL_CHARGE_NUM' => '1','SPECIAL_CHARGE_DESCRIPTION' => 'Heavy','SPECIAL_CHARGE_AMOUNT' => '75.00'),
  array('SPECIAL_CHARGE_NUM' => '2','SPECIAL_CHARGE_DESCRIPTION' => 'Fragile','SPECIAL_CHARGE_AMOUNT' => '70.00'),
  array('SPECIAL_CHARGE_NUM' => '3','SPECIAL_CHARGE_DESCRIPTION' => 'Handling','SPECIAL_CHARGE_AMOUNT' => '25.00'),
  array('SPECIAL_CHARGE_NUM' => '4','SPECIAL_CHARGE_DESCRIPTION' => 'Special','SPECIAL_CHARGE_AMOUNT' => '50.00'),
  array('SPECIAL_CHARGE_NUM' => '5','SPECIAL_CHARGE_DESCRIPTION' => 'Large','SPECIAL_CHARGE_AMOUNT' => '50.00'),
  array('SPECIAL_CHARGE_NUM' => '6','SPECIAL_CHARGE_DESCRIPTION' => 'Glass','SPECIAL_CHARGE_AMOUNT' => '20.00'),
  array('SPECIAL_CHARGE_NUM' => '7','SPECIAL_CHARGE_DESCRIPTION' => 'Flammable','SPECIAL_CHARGE_AMOUNT' => '25.00'),
  array('SPECIAL_CHARGE_NUM' => '8','SPECIAL_CHARGE_DESCRIPTION' => 'Dangerous','SPECIAL_CHARGE_AMOUNT' => '50.00'),
  array('SPECIAL_CHARGE_NUM' => '9','SPECIAL_CHARGE_DESCRIPTION' => 'High Value','SPECIAL_CHARGE_AMOUNT' => '75.00'),
  array('SPECIAL_CHARGE_NUM' => '10','SPECIAL_CHARGE_DESCRIPTION' => 'Low Qty','SPECIAL_CHARGE_AMOUNT' => '20.00')
);

/* `holts`.`TERRITORY` */
$TERRITORY = array(
  array('TERRITORY_NUM' => '1','TERRITORY_NAME' => 'East1'),
  array('TERRITORY_NUM' => '2','TERRITORY_NAME' => 'East2'),
  array('TERRITORY_NUM' => '3','TERRITORY_NAME' => 'East3'),
  array('TERRITORY_NUM' => '4','TERRITORY_NAME' => 'South1'),
  array('TERRITORY_NUM' => '5','TERRITORY_NAME' => 'South2'),
  array('TERRITORY_NUM' => '6','TERRITORY_NAME' => 'West1'),
  array('TERRITORY_NUM' => '7','TERRITORY_NAME' => 'West2'),
  array('TERRITORY_NUM' => '8','TERRITORY_NAME' => 'West3'),
  array('TERRITORY_NUM' => '9','TERRITORY_NAME' => 'North1'),
  array('TERRITORY_NUM' => '10','TERRITORY_NAME' => 'North2')
);

/* `holts`.`VENDOR` */
$VENDOR = array(
  array('VENDOR_NUM' => '1','VENDOR_NAME' => 'Killian Wolfe','VENDOR_ADDRESS' => '761 Harvey St.','VENDOR_CITY' => 'Farmingdale','VENDOR_STATE' => 'NY','VENDOR_ZIP' => '11735'),
  array('VENDOR_NUM' => '2','VENDOR_NAME' => 'Muhamed Cassidy','VENDOR_ADDRESS' => '8030 W. Paris Hill Ave.','VENDOR_CITY' => 'Pudacah','VENDOR_STATE' => 'KY','VENDOR_ZIP' => '42001'),
  array('VENDOR_NUM' => '3','VENDOR_NAME' => 'Rehan Doyle','VENDOR_ADDRESS' => '322 Plymouth St.','VENDOR_CITY' => 'La Crosse','VENDOR_STATE' => 'WI','VENDOR_ZIP' => '54601'),
  array('VENDOR_NUM' => '4','VENDOR_NAME' => 'Willie Gillespie','VENDOR_ADDRESS' => '7187 Cambridge St.','VENDOR_CITY' => 'Lowell','VENDOR_STATE' => 'MA','VENDOR_ZIP' => '01851'),
  array('VENDOR_NUM' => '5','VENDOR_NAME' => 'Karla Bateman','VENDOR_ADDRESS' => '33 Jockey Hollow Circle','VENDOR_CITY' => 'Fremont','VENDOR_STATE' => 'OH','VENDOR_ZIP' => '43420'),
  array('VENDOR_NUM' => '6','VENDOR_NAME' => 'Sabiha Coles','VENDOR_ADDRESS' => '14 Cedar Dr.','VENDOR_CITY' => 'Honolulu','VENDOR_STATE' => 'HI','VENDOR_ZIP' => '96815'),
  array('VENDOR_NUM' => '7','VENDOR_NAME' => 'Ammarah Handley','VENDOR_ADDRESS' => '8382 Lyme Dr.','VENDOR_CITY' => 'Hagerstown','VENDOR_STATE' => 'MD','VENDOR_ZIP' => '21740'),
  array('VENDOR_NUM' => '8','VENDOR_NAME' => 'Karishma Joseph','VENDOR_ADDRESS' => '8590 N. Roehampton Rd.','VENDOR_CITY' => 'Kernersville','VENDOR_STATE' => 'NC','VENDOR_ZIP' => '27284'),
  array('VENDOR_NUM' => '9','VENDOR_NAME' => 'Shona Villa','VENDOR_ADDRESS' => '999 Gulf Ave.','VENDOR_CITY' => 'Rego Park','VENDOR_STATE' => 'NY','VENDOR_ZIP' => '11374'),
  array('VENDOR_NUM' => '10','VENDOR_NAME' => 'Reyansh Mosley','VENDOR_ADDRESS' => '9956 N. Grand St.','VENDOR_CITY' => 'Monsey','VENDOR_STATE' => 'NY','VENDOR_ZIP' => '10952')
);

/* `holts`.`VENDOR_PART` */
$VENDOR_PART = array(
  array('VENDOR_PART_NUM' => '1','VENDOR_PART_PRICE' => '150.00','MIN_ORDER_QUANTITY' => '20','PART_LEAD_TIME' => '5','PART_NUM' => '4','VENDOR_NUM' => '6'),
  array('VENDOR_PART_NUM' => '2','VENDOR_PART_PRICE' => '475.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '7','PART_NUM' => '6','VENDOR_NUM' => '3'),
  array('VENDOR_PART_NUM' => '3','VENDOR_PART_PRICE' => '65.00','MIN_ORDER_QUANTITY' => '20','PART_LEAD_TIME' => '10','PART_NUM' => '9','VENDOR_NUM' => '3'),
  array('VENDOR_PART_NUM' => '4','VENDOR_PART_PRICE' => '45.00','MIN_ORDER_QUANTITY' => '30','PART_LEAD_TIME' => '7','PART_NUM' => '3','VENDOR_NUM' => '6'),
  array('VENDOR_PART_NUM' => '5','VENDOR_PART_PRICE' => '145.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '8','PART_NUM' => '5','VENDOR_NUM' => '8'),
  array('VENDOR_PART_NUM' => '6','VENDOR_PART_PRICE' => '225.00','MIN_ORDER_QUANTITY' => '30','PART_LEAD_TIME' => '5','PART_NUM' => '1','VENDOR_NUM' => '10'),
  array('VENDOR_PART_NUM' => '7','VENDOR_PART_PRICE' => '135.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '12','PART_NUM' => '2','VENDOR_NUM' => '8'),
  array('VENDOR_PART_NUM' => '8','VENDOR_PART_PRICE' => '175.00','MIN_ORDER_QUANTITY' => '20','PART_LEAD_TIME' => '3','PART_NUM' => '5','VENDOR_NUM' => '7'),
  array('VENDOR_PART_NUM' => '9','VENDOR_PART_PRICE' => '150.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '5','PART_NUM' => '4','VENDOR_NUM' => '5'),
  array('VENDOR_PART_NUM' => '10','VENDOR_PART_PRICE' => '75.00','MIN_ORDER_QUANTITY' => '30','PART_LEAD_TIME' => '8','PART_NUM' => '10','VENDOR_NUM' => '3'),
  array('VENDOR_PART_NUM' => '11','VENDOR_PART_PRICE' => '550.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '9','PART_NUM' => '8','VENDOR_NUM' => '4'),
  array('VENDOR_PART_NUM' => '12','VENDOR_PART_PRICE' => '235.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '5','PART_NUM' => '7','VENDOR_NUM' => '1'),
  array('VENDOR_PART_NUM' => '13','VENDOR_PART_PRICE' => '75.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '10','PART_NUM' => '4','VENDOR_NUM' => '2'),
  array('VENDOR_PART_NUM' => '14','VENDOR_PART_PRICE' => '335.00','MIN_ORDER_QUANTITY' => '20','PART_LEAD_TIME' => '2','PART_NUM' => '10','VENDOR_NUM' => '8'),
  array('VENDOR_PART_NUM' => '15','VENDOR_PART_PRICE' => '50.00','MIN_ORDER_QUANTITY' => '35','PART_LEAD_TIME' => '5','PART_NUM' => '4','VENDOR_NUM' => '9'),
  array('VENDOR_PART_NUM' => '16','VENDOR_PART_PRICE' => '75.00','MIN_ORDER_QUANTITY' => '35','PART_LEAD_TIME' => '7','PART_NUM' => '7','VENDOR_NUM' => '4'),
  array('VENDOR_PART_NUM' => '17','VENDOR_PART_PRICE' => '360.00','MIN_ORDER_QUANTITY' => '30','PART_LEAD_TIME' => '3','PART_NUM' => '9','VENDOR_NUM' => '5'),
  array('VENDOR_PART_NUM' => '18','VENDOR_PART_PRICE' => '230.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '8','PART_NUM' => '6','VENDOR_NUM' => '2'),
  array('VENDOR_PART_NUM' => '19','VENDOR_PART_PRICE' => '340.00','MIN_ORDER_QUANTITY' => '25','PART_LEAD_TIME' => '2','PART_NUM' => '9','VENDOR_NUM' => '9'),
  array('VENDOR_PART_NUM' => '20','VENDOR_PART_PRICE' => '145.00','MIN_ORDER_QUANTITY' => '30','PART_LEAD_TIME' => '6','PART_NUM' => '8','VENDOR_NUM' => '5')
);
